apiVersion: v1
kind: Service
metadata:
  labels:
      app: noticias
  name: php7app
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
      app: noticias
  sessionAffinity: None
  type: ClusterIP
