---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php7-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php7
    spec:
      containers:
      - name: php7
        image: rabellamy/php7
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /var/www/html
          name: src
      volumes:
      - name: src
        hostPath:
          path: /Users/scottrigby/development/NGINX-PHP-7-K8S-Deployment/src
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: rabellamy/nginx
        ports:
        - containerPort: 80
