---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php7-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php7
    spec:
      containers:
      - name: php7
        image: r6by/php7:0.5.9
        ports:
        - containerPort: 9000
