apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: NGINX_SERVER_NAME
            value: {{ .Release.Name }}-drupal
          - name: NGINX_SERVER_ROOT
            value: {{ default "/var/www/html/vendor/drupal/drupal" .Values.serverRoot | quote }}
          - name: NGINX_STATIC_CONTENT_ACCESS_LOG
            value: {{ default "off" .Values.accessLog | quote }}
          - name: NGINX_STATIC_CONTENT_EXPIRES
            value: {{ default "30d" .Values.expires | quote }}
          - name: NGINX_STATIC_CONTENT_OPEN_FILE_CACHE
            value: {{ default "max=3000 inactive=120s" .Values.openFileCache | quote }}
          - name: NGINX_STATIC_CONTENT_OPEN_FILE_CACHE_VALID
            value: {{ default "45s" .Values.openFileValid | quote }}
          - name: NGINX_STATIC_CONTENT_OPEN_FILE_CACHE_MIN_USES
            value: {{ default "2" .Values.openFileCacheMinUses | quote }}
          - name: NGINX_ALLOW_XML_ENDPOINTS
            value: {{ default true .Values.allowXMLEndpoints | quote }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
